### ISSUE TITLE
exercise 1

### ISSUE THREAD

**Issue by 19901124** [hasanisaeed/python-course#12]
![Capture](https://user-images.githubusercontent.com/126291939/221373137-822c3d48-78a2-49c2-80f7-6622f8982fc5.PNG)

**Comment by hasanisaeed** [comment]
خیلی عالی

سوال 4 رو دوباره حل میکنین؟
و نتیجه اش رو اینجا بذارین


راستی عکس نگیرین
از قابلیت خودت گیت‌هاب استفاده کنین.

وقتی میخواین کد بزنین، گزینه <>  رو انتخاب کنین و کدهاتون بذارین. اینطوری خیلی تمیز تر می‌شه. سوالی داشتین حتما بپرسین

**Comment by hasanisaeed** [comment]
اینجا رو ببینین یکی از بچه ها فرستاده:
https://github.com/hasanisaeed/python-course/issues/7#issuecomment-1443362610

**Comment by hasanisaeed** [comment]
سوالی براتون پیش اومده حتما بپرسین
با سوال پرسیدن یاد میگیرین
