### ISSUE TITLE
سوال در مورد مقدار اعشار در خروجی 

### ISSUE THREAD

**Issue by behnamslash** [hasanisaeed/python-course#14]
```python

x=2*pi
print(x)

6.28

```

استاد سلام چرا اعداد  به صورت چند رقم اعشار خروجی نمیده

**Comment by hasanisaeed** [comment]
لطفا عنوان issue رو یه عنوان مناسب بذار.

و نکته دیگه سعی کن از کدت عکس نگیری بفرستی. 
مثل این کامنت کدت رو بذار
[#7](https://github.com/hasanisaeed/python-course/issues/7#issuecomment-1443362610)

**Comment by behnamslash** [comment]
مرسی استاد بابت راهنمایی  
#14

**Comment by hasanisaeed** [comment]
این لینک رو ببین کمکت میکنه:

https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

**Comment by behnamslash** [comment]
```mersi ostad 

```

**Comment by behnamslash** [comment]
```python code for learning
x=2*pi
print(x)

6.28

```

مرسی استاد متوجه شدم
