### ISSUE TITLE
سوالات و مشکلات احتمالی گیت 

### ISSUE THREAD

**Issue by hasanisaeed** [hasanisaeed/python-course#5]
اگه توی نصب گیت به مشکل خوردین لطفا مشکلات تون رو اینجا مطرح کنین. همه رو جواب میدم.

> سوالات تون درباره گیت اینجا مطرح کنین.

**Comment by hasanisaeed** [comment]
توی این لینک دوباره من توضیحات امروز رو مرور کردم.

[گیت / فورک / کلون و... ](https://www.aparat.com/v/VFQnt)

**Comment by Hesam-Norozi** [comment]
![Screenshot (53) - Copy](https://user-images.githubusercontent.com/125771440/221277016-c3d977f0-d4ca-45c8-b6a9-85ebd4f577b6.png)
سلام وقت بخیر مهندس
وقتی میخوام از ریپویی که ایجاد کردین فورک بگیرم با فرمت SSH با خطای بالا مواجه میشم
اما با فرمت https با خطایی مواجه نمیشم
مشکل از کجاست واینکه تفاوت بین دو فرمت و git hub cli چی هست؟

**Comment by hasanisaeed** [comment]
> وقتی میخوام از ریپویی که ایجاد کردین فورک بگیرم با فرمت SSH با خطای بالا مواجه میشم

سلام حسام جان
گزینه yes رو بزن ببین اوکی میشه یا نه؟

**Comment by hasanisaeed** [comment]
> اما با فرمت https با خطایی مواجه نمیشم

احراز هویت با `SSH` با یوزر ئسورد (که همون `https` هست) کاملا متفاوت هست.
یه لینک پیدا کنم براتون میفرستم الان

**Comment by hasanisaeed** [comment]
> مشکل از کجاست واینکه تفاوت بین دو فرمت و git hub cli چی هست؟

ببین گیت خودش یه چیز public هست یعنی شرکتهایی دیگه مثل gitlab.com هم دارن استفاده میکنن.  و دستورات گیت توی همه این شرکتها یکی هست. اما github cli چیه؟ 
گیت هاب باز خودش اومده علاوه بر دستورات public گیت، یه سری دستورات دیگه رو اضافه کرده که کار کردن با سایتش که همین github.com هست راحت تر بشه. اون github cli مخفف `github command line ` هست.

**Comment by hasanisaeed** [comment]
@Hesam-Norozi 

### برای اینکه از SSH استفاده کنین لطفا این لینک رو ببین

 [اتصال به گیت هاب با فعالسازی SSH](https://www.aparat.com/v/6KQRL)

**Comment by Hesam-Norozi** [comment]
> 
![Screenshot (54)](https://user-images.githubusercontent.com/125771440/221373234-a8f2bea1-f7cf-4d99-aa8c-9e35c3ddc68c.png)
وقتی گزینه yes  رو میزنم با متن بالا مواجه میشم

**Comment by TheOtherGuy369** [comment]
[> > 
> 
> ![Screenshot (54)](https://user-images.githubusercontent.com/125771440/221373234-a8f2bea1-f7cf-4d99-aa8c-9e35c3ddc68c.png) وقتی گزینه yes رو میزنم با متن بالا مواجه میشم

(https://bbs.archlinux.org/viewtopic.php?id=264254)
شاید کمک کنه...

**Comment by hasanisaeed** [comment]
وقتی گزینه yes رو میزنم با متن بالا مواجه میشم

خطا میتونه به این علت باشه که ریپو تون private هست و وقتی از SSH استفاده میکنین باید public key تون به گیت هاب بدین.
متوجه نشدین حضوری ازم بپرسین

**Comment by hasanisaeed** [comment]
این ایشو رو میبندم.
اگه نیاز بود باز بشه، میتونین بازش کنین
